### ISSUE TITLE
html font-size/line-height is broken since correct units implemented

### ISSUE THREAD

**Issue by stowball** [chris-pearce/scally#103]
After https://github.com/chris-pearce/scally/pull/95 was merged, the `font` shorthand rule in `_root.scss` has broken, as it's treating it all as a mathematical operation.

Instead of `font: 1em/1.5 Arial, sans-serif;`, we now get `font: 0.66667em Arial, sans-serif;`

**Comment by chris-pearce** [comment]
Yep I seen this late last night when testing a V2 feature, I fixed in V2 and I'll push a fix for V1 right away.

Can you label Issues :+1:.

**Comment by stowball** [comment]
Ah, I didn't know that I could! I've never looked up there before :)
