### ISSUE TITLE
Go through Sass Guidelines to see what could be useful for Scally

### ISSUE THREAD

**Issue by chris-pearce** [chris-pearce/scally#107]
Some good stuff in @HugoGiraudel guidelines: http://sass-guidelin.es/.

**Comment by KittyGiraudel** [comment]
Sass Guidelines is a highly opinionated guide to write Sass code. While rules might not all suit your team or preferences, the key word here is _consistency_.

Having read through the whole source of Scally, I must say it would be nice if the code could be a little more consistent. Linting and sticking to coding guidelines would help in that way.

**Comment by chris-pearce** [comment]
I'm mostly referring to your functions/mixins in your Guidelines e.g. http://sass-guidelin.es/#lightening-and-darkening-colors. As for authoring guidelines Scally adheres to: https://github.com/chris-pearce/css-guidelines.

I hear you about consistency. I for one keep an eye on this as I can't stand inconsistently formatted code, ask anyone who works with me :)

> > Having read through the whole source of Scally, I must say it would be nice if the code could be a little more consistent. Linting and sticking to coding guidelines would help in that way.

Impressed you've read through all the source. Linting has been setup for Scally: https://github.com/chris-pearce/scally/blob/master/.scss-lint.yml and is mentioned in the docs: https://github.com/chris-pearce/scally#linting and it will be applied automatically via CI: https://github.com/chris-pearce/scally/issues/21. Be great to get some specific feedback from you as to what you find inconsistent. Thanks.

**Comment by KittyGiraudel** [comment]
On the top of my head:
- sometimes you inline CSS rules, sometimes you don't
- sometimes you use Sass comments, sometimes CSS'
- sometimes you end comment with full-stop, sometimes you don't
- I haven't noticed any declarations order, but I might have overlooked it
- sometimes indentation is broken
- sometimes you use `//endif` comment (why?), sometimes you don't
- empty lines usage is highly inconsistent
- sometimes you quote strings, sometimes you don't

**Comment by chris-pearce** [comment]
Thanks for that feedback @HugoGiraudel, appreciate it.

Some of those feedback items are following the Scally guidelines (surprisingly) however I plan to look at the Guidelines again as it's been a while since they were written, and make some changes. 

I'll create an issue to fix up some of those things and to change some of the guidelines to align with how I'm used to writing CSS at my workplace e.g. remove indentation to reflect the DOM, don't have single line declarations not on a new line, etc.
