### ISSUE TITLE
New component: Fancy `select`

### ISSUE THREAD

**Issue by chris-pearce** [chris-pearce/scally#12]

**Comment by chris-pearce** [comment]
Will look at @chriswrightdesign's lib for this or just not bother and recommend people use that instead?

**Comment by chriswrightdesign** [comment]
Have a look, see if it works for you. I have to test it in JAWS still.

**Comment by chris-pearce** [comment]
Gonna close this, any custom form things I'd use: http://chriswrightdesign.github.io/customforms/.
