### ISSUE TITLE
Why does hr have 2 border rules?

### ISSUE THREAD

**Issue by stowball** [chris-pearce/scally#122]
The hr component has a `border: 0`, then the Scally/user-defined `border`. Why?
https://github.com/chris-pearce/scally/blob/master/core/base/_horizontal-rule.scss#L20

**Comment by chris-pearce** [comment]
That's a bug, it should be `border-top` as per: https://github.com/h5bp/html5-boilerplate/blob/master/dist/css/main.css#L41-L48.
