### ISSUE TITLE
Provide a "retina" media query mixin

### ISSUE THREAD

**Issue by stowball** [chris-pearce/scally#123]
It's hard to remember the syntax for different resolution media queries, so it would be great if a retina media query mixin was provided so all media queries in a Scally project are written with mixins.

The default should be for a 1.5dpr as that caters for most devices, but also allow it to be customised for 2dpr.

CSS Tricks has a list of the syntaxes: https://css-tricks.com/snippets/css/retina-display-media-query/ but we only need the unprefixed `min-resolution` as autoprefixer will take care of the `-webkit-min-device-pixel-ratio`

**Comment by chris-pearce** [comment]
There's this one specifically for bg images: https://github.com/chris-pearce/scally/blob/master/core/mixins/_retina-bg-image.scss.

**Comment by stowball** [comment]
Hmmm didn't see that. I wonder if there other use cases for a separate retina mixin that allows any `@content`…?

Perhaps just update this to allow for different resolutions and remove the prefixes?

Also, perhaps have `$width` and `$height` to default to `auto`, that way you only need to calculate one dimension:

``` scss
a {
  @include retina-bg-image(foo@2x.png, 100px);
}
```

Which would result in:

``` css
a {
  background-size: 100px auto;
}
```

**Comment by chris-pearce** [comment]
> Hmmm didn't see that. I wonder if there other use cases for a separate retina mixin that allows any `@content`…?

I can't think of any of the top of my head.

> Perhaps just update this to allow for different resolutions and remove the prefixes?

Will do.

> Also, perhaps have $width and $height to default to auto, that way you only need to calculate one dimension:

Yes good shout.

**Comment by stowball** [comment]
In my brief search, I can't find any good info on what a good, default dpr is to match most devices. [Suzi uses 1.3](https://github.com/stowball/Suzi/blob/master/css/core/_mixins.scss#L296), but Scally uses 1.25.

It'd be great to allow users to input any ratio they want, though and not limit them to set ones (so that way it doesn't need to keep up with 3x and 4x devices should we ever need to cater for them specifically).

1dpr = 96dpi, so take whatever (unitless) dpr they enter and multiply it by 96 to get the desired dpi.

**Comment by stowball** [comment]
After doing a search for sass media query mixins, it seems like a lot frameworks/developers like to have a separate mixin that can be passed any `@content`. Bourbon is a high profile one (which also does the DPR stuff with a 1.3 default):  http://bourbon.io/docs/#hidpi-media-query

The more I think about it, the more I agree with my original request to provide a "just" retina mixin, to:
- give users choice as to how they write their retina rules (lots of devs don't like mixins that do too much for them)
- allow devs to write "normal" css to benefit from code hints and not use arguments
- allow easier transition from other frameworks that provide this already
- not confuse new devs (like myself) when they don't see one in the media queries partial & think they have to write their own

Is still keep the original for backwards compatibility though & users who prefer that way.
