### ISSUE TITLE
u-widths should be layout

### ISSUE THREAD

**Issue by chriswrightdesign** [chris-pearce/scally#129]
The utilities for widths are layout related, I'd argue that the u-widths partial should be a layout namespace not a utility namespace as they relate purely to layout

**Comment by kllevin** [comment]
I think this is something worth discussing, but should be flagged for v3, as it would be a breaking change.

**Comment by stowball** [comment]
I've used them in form inputs and table cells, so imo they have a more generic role than just layout

**Comment by chris-pearce** [comment]
Before I started building Scally I did extensive research of other frameworks and a common treatment was how widths were tied to specific layout components e.g. a grid making reusing those widths impossible for other things. 

I wanted the Scally % widths to be able to be applied to any element and even though they're used a lot on layout modules like the grid they are not purely related to layout so I think they're well suited as utilities.

**Comment by chriswrightdesign** [comment]
I guess I've always viewed anything regarding width (regardless of whether it's a grid component or not) to be in layout. So most other frameworks would regard this as utility?

**Comment by chris-pearce** [comment]
A common use case is applying a width to a text input element e.g.

``` html
<input type="text" class="u-one-half">
```

To me this isn't layout its just making the text input 50% wide. Same with table cells. As I said these kind of treatments can be rare and usually would be sucked up into a specific component however they do occur and to me they aren't layout esp in the context of Scally layout modules.

> So most other frameworks would regard this as utility?

The good ones yes e.g.
- [Inuit](https://github.com/inuitcss/tools.widths/blob/master/_tools.widths.scss)
- [SUIT](https://github.com/suitcss/utils-size/blob/master/lib/size.css)

**Comment by chris-pearce** [comment]
Oh yeah @chriswrightdesign if you could label your issues that would be great :+1:.
