### ISSUE TITLE
Typo in Scally Components

### ISSUE THREAD

**Issue by netfront** [chris-pearce/scally#151]
The second paragraph located @ https://github.com/chris-pearce/scally/tree/master/components#what-are-they requires updates in the text. From 'i.e. where the live in a UI' to 
'where the component lives in the UI' OR 'where they live in the UI'.

![scally](https://cloud.githubusercontent.com/assets/5026667/8104442/1162616a-1074-11e5-8040-2c28e345bba6.PNG)

**Comment by chris-pearce** [comment]
Cheers @netfront, will get that fixed :+1:
