### ISSUE TITLE
`apply-details-marker` settings is confusing

### ISSUE THREAD

**Issue by kllevin** [chris-pearce/scally#176]
The setting to show the default marker for a details element reads backward to me. 

`$apply-details-marker: false` means to show the default marker

`$apply-details-marker: true` means hide it.

I think these should be reversed for clarity. This will need to wait until V3.

**Comment by chris-pearce** [comment]
Thanks and yes it is confusing. It'll get fixed in V3 so I'll close this as it's logged [here](https://github.com/chris-pearce/scally/issues/126).
