### ISSUE TITLE
Remove references to lap small and desk small from the documentation

### ISSUE THREAD

**Issue by kllevin** [chris-pearce/scally#182]
We removed these preset breakpoints ages ago but didn't remove the references to them in the documentation. Can we remove?

https://github.com/chris-pearce/scally/blob/master/core/settings/_breakpoints.scss#L17-L26

**Comment by chris-pearce** [comment]
Good catch.

**Comment by chris-pearce** [comment]
Closing this as this will be resolved in the soon to be released next major version: **3.0.0**.
