### ISSUE TITLE
Make all Scally modules be standalone

### ISSUE THREAD

**Issue by chris-pearce** [chris-pearce/scally#190]
If you want to just use the **Grid** you should be able to without needing anything else. Not sure if this is possible without at least **Settings** and **Normalise/Reset**?

**Comment by kllevin** [comment]
Could look at ways to split up settings, so at least you only get the settings related to the module you want to use? Not sure if it is worth it?

**Comment by chris-pearce** [comment]
Then you go back to the v2 model of having to override settings above the relevant partial in your master stylesheet, which just feels yuk 😷.

Not sure if this is worth doing? I think `_settings.scss` is always going to be needed but that's the only core dependency.

**Comment by chris-pearce** [comment]
Not worth it seeing as you have to break up all the settings like V2 which I really don't like.
