### ISSUE TITLE
Documentation updates and additions

### ISSUE THREAD

**Issue by chris-pearce** [chris-pearce/scally#31]
- Write up about applying utilities, objects, layout modules at breakpoints.
- Write up about Scally's core unit (`rem`) and the places where `px` are used, and how Scally supports unitless and units.
- How to compile in LibSass
  
  ```
  npm install node-sass -g
  node-sass style.scss style-node.css
  ```
- Some **Further reading** links:
  - http://philipwalton.com/articles/extending-styles/

**Comment by kllevin** [comment]
Consider adding a section specifically dealing with `u-spacing`?

**Comment by chris-pearce** [comment]
Yeah I think that's needed. Could you read the current documentation: https://github.com/chris-pearce/scally/blob/master/utilities/README.md#applying-at-breakpoints and let me know what's missing? I think the actual code needs more documentation also.
