### ISSUE TITLE
Licensing compliance

### ISSUE THREAD

**Issue by thiagofigueiro** [chris-pearce/scally#32]
Chris, it's great that you're continuing the work in Scally - it shows you passion.

I must, however, ask that you follow the original licence of the software.  

One is not allowed to change the licence from Apache 2 to MIT for code created by Westfield Labs.  One must also keep the Westfield Labs copyright, even though you're granted a licence to redistribute.

Any extra work you add can be licensed as you see fit.

Please refer to section 4 of the Apache Licence and correct your repository for compliance.

Thank you
1. Redistribution. You may reproduce and distribute copies of the
     Work or Derivative Works thereof in any medium, with or without
     modifications, and in Source or Object form, provided that You
     meet the following conditions:
   
     (a) You must give any other recipients of the Work or
         Derivative Works a copy of this License; and
   
     (b) You must cause any modified files to carry prominent notices
         stating that You changed the files; and
   
     (c) You must retain, in the Source form of any Derivative Works
         that You distribute, all copyright, patent, trademark, and
         attribution notices from the Source form of the Work,
         excluding those notices that do not pertain to any part of
         the Derivative Works; and
   
     (d) If the Work includes a "NOTICE" text file as part of its
         distribution, then any Derivative Works that You distribute must
         include a readable copy of the attribution notices contained
         within such NOTICE file, excluding those notices that do not
         pertain to any part of the Derivative Works, in at least one
         of the following places: within a NOTICE text file distributed
         as part of the Derivative Works; within the Source form or
         documentation, if provided along with the Derivative Works; or,
         within a display generated by the Derivative Works, if and
         wherever such third-party notices normally appear. The contents
         of the NOTICE file are for informational purposes only and
         do not modify the License. You may add Your own attribution
         notices within Derivative Works that You distribute, alongside
         or as an addendum to the NOTICE text from the Work, provided
         that such additional attribution notices cannot be construed
         as modifying the License.
   
     You may add Your own copyright statement to Your modifications and
     may provide additional or different license terms and conditions
     for use, reproduction, or distribution of Your modifications, or
     for any such Derivative Works as a whole, provided Your use,
     reproduction, and distribution of the Work otherwise complies with
     the conditions stated in this License.

**Comment by chris-pearce** [comment]
Thiago, 

Sorry about my ignorance around the licensing and copyrighting. I believe I have made the adjustments you're wanting? [See here](https://github.com/chris-pearce/scally/blob/master/README.md#license).

If that doesn't suit please let me know what else I am missing.

Thanks
