### ISSUE TITLE
Add new spacing utilities to cater for halves

### ISSUE THREAD

**Issue by chris-pearce** [chris-pearce/scally#34]
Should be able to apply halves e.g. `.u-s-m-half-small`.

**Comment by kllevin** [comment]
I feel like this might be a bit overkill. You can tweak the settings of these to match your needs. Not sure how necessary it is?

**Comment by chris-pearce** [comment]
@kllevin I've been finding that I need this more and more when building UI.

**Comment by chris-pearce** [comment]
@kllevin you're right—it's overkill. Killing this.

▄︻̷̿┻̿═━一
