### ISSUE TITLE
Applying spacing utilities at breakpoints not working

### ISSUE THREAD

**Issue by chris-pearce** [chris-pearce/scally#35]
```
$u-spacing-apply-at-breakpoints: (lap);
$u-spacing-apply-classes-for-breakpoints: (base, micro, small, large, huge);
@import "scally/utilities/u-spacing";
```

Tried the above and many different variations and nothing is rendered.

**Comment by kllevin** [comment]
Not a bug.

The format is:

```
$u-spacing-apply-classes-for-breakpoints: (
   ".u-s-pe-base",
   ".u-s-pe-none");
```

The documentation around this appears to be non-existent, and the comments in the u-spacing file is confusing.

**Comment by chris-pearce** [comment]
@kllevin thanks for looking into this and I agree that more documentation, especially in the `u-spacing` file, is needed which is why I created this issue: #31.

Right now this is what Scally has in terms of documentation around this: https://github.com/chris-pearce/scally/blob/master/utilities/README.md#applying-at-breakpoints. Feel free to add to it.
