### ISSUE TITLE
Consider name spacing components

### ISSUE THREAD

**Issue by chris-pearce** [chris-pearce/scally#41]
Using `c-`. Inspired by: http://csswizardry.com/2015/03/more-transparent-ui-code-with-namespaces/.

@kllevin @stowball what do you think?

**Comment by stowball** [comment]
I like it, but I also wonder whether it's overkill in a "normal", new situation. Everything not namespaced would be a component, right?

However, in terms of our legacy codebase that we're integrating with, it could be very useful for us to quickly see what's "new world"

**Comment by kllevin** [comment]
I would lean toward name spacing. All the other sections of the framework are name spaced so it is more consistent. Beyond the typical protection from collisions argument, it will also create a separation between components from the framework and custom project level components. I find it frustrating to scan a list of components and not be able to tell what was developed by my team, and what we are extending from a framework (Foundation in this case, but same idea).

**Comment by chris-pearce** [comment]
I'm gonna do this.

**Comment by chris-pearce** [comment]
Addressed in #74.
