### ISSUE TITLE
How to work out base line-height when base font-size changes

### ISSUE THREAD

**Issue by chris-pearce** [chris-pearce/scally#46]
When changing this: https://github.com/chris-pearce/scally/blob/master/core/settings/_typography.scss#L11 you also need to change this: https://github.com/chris-pearce/scally/blob/master/core/settings/_typography.scss#L49 but how?

**Comment by stowball** [comment]
Instead of explicitly setting the line-height, perhaps setting the ratio would be more future-friendly.

```
$line-height-ratio: 1.5 !default; 
$line-height: $font-size * $line-height-ratio !default;
```

This way, whether or not a user changes the line-height-ratio, the line-height would always be a ratio to the font-size, so would create some level of desired spacing

**Comment by kllevin** [comment]
Thank you! And I agree, change it so the value isn't hard-coded.

**Comment by chris-pearce** [comment]
Doing this:

```
$line-height-ratio: 1.5 !default; 
$line-height: $font-size * $line-height-ratio !default;
```

Results in a line height of **24** if the font size remains at **16** (the default) unless I'm missing something here?

**Comment by stowball** [comment]
Correct. But if a user of Scally only changes the font-size to say 20px, the line-height will now be 30px (20 \* 1.5) as opposed to the hard 24px - so some kind of appropriate vertical spacing/rhythm will be maintained.

**Comment by chris-pearce** [comment]
How do we get it be a unitless value not a **px** value as Scally uses unitless line heights?

BTW the Scally [font-size mixin](https://github.com/chris-pearce/scally/blob/master/core/mixins/_font-size.scss) which is used for declaring ALL font sizes e.g. `@include font-size(24);` automatically works out the most optimal line height via [this calculation](https://github.com/chris-pearce/scally/blob/master/core/mixins/_font-size.scss#L58-L59).

The current setup is taken from Inuit:

https://github.com/inuitcss/settings.defaults/blob/master/_settings.defaults.scss
https://github.com/inuitcss/base.page/blob/master/_base.page.scss#L20-L21
https://github.com/inuitcss/tools.mixins/blob/master/_tools.mixins.scss#L57-L77

**Comment by stowball** [comment]
It would still be unitless; it's not changing anything under the hood. It's just that you're letting the use define a ratio instead of a hard value so it's scalable
