### ISSUE TITLE
Create a new section called: Objects and convert some utilities to objects

### ISSUE THREAD

**Issue by chris-pearce** [chris-pearce/scally#47]
Some candidates:
- [Flex emded](https://github.com/chris-pearce/scally/blob/master/utilities/_u-flex-embed.scss)
- [Link complex](https://github.com/chris-pearce/scally/blob/master/utilities/_u-link-complex.scss)
- [Link disguised](https://github.com/chris-pearce/scally/blob/master/utilities/_u-link-disguised.scss)
- [Overlay](https://github.com/chris-pearce/scally/blob/master/utilities/_u-overlay.scss)
- [Table](https://github.com/chris-pearce/scally/blob/master/utilities/_u-table.scss)
- [Drop down](https://github.com/chris-pearce/scally/blob/master/utilities/_u-drop-down.scss)
- [List block](https://github.com/chris-pearce/scally/blob/master/utilities/_u-list-block.scss)
  or this goes as logged here: #44? 

@kllevin @AlecRaeside @stowball what do you guys think?

**Comment by stowball** [comment]
Great idea.

Flex-embed, Link complex and Drop down definitely make a lot of sense because you there are multiple elements that all depend on various classes. The others could definitely be contenders too, depending how their normal use-case is represented as markup.

**Comment by chris-pearce** [comment]
Going to do this tomorrow it's looking, won't be backwards compatible change though.

**Comment by kllevin** [comment]
I would convert list to a component. Would arrow just go? I can see it becoming part of other components? Not sure if we want to create components that rely on other components. Such as a dropdown or list having the option to suck in the arrow as an indicator/bullet style?

**Comment by chris-pearce** [comment]
@kllevin did you see: https://github.com/chris-pearce/scally/issues/61?

**Comment by chris-pearce** [comment]
> > Would arrow just go?

I think **Arrow** is a utility the more I think about it as it's so low level and only needs to be work on 1 element.

> > Not sure if we want to create components that rely on other components.

I agree, feels weird as it goes against one of the main definitions of a component which is a discrete piece of UI that can stand-alone. Which is why I struggle with **List inline** as for sure that'll be needed in a lot of components hence why I'm thinking it's a layout module (minus some of it's modifiers, maybe?) as at it's core it is concerned with structural CSS like the **Grid**? It's the same as **Drop down** as it's used mostly as the start of a richer component so maybe it remains a low level utility?

**Comment by chris-pearce** [comment]
@stowball @chriswrightdesign @kllevin I'm seriously thinking we need a new section in Scally called something like: **Objects** which houses utilities like **List Inline**, **Drop Down**, **Flex Embed**, etc. I've been looking at this: http://csswizardry.com/2015/03/more-transparent-ui-code-with-namespaces/ esp these sections:
- http://csswizardry.com/2015/03/more-transparent-ui-code-with-namespaces/#utility-namespaces-u-
- http://csswizardry.com/2015/03/more-transparent-ui-code-with-namespaces/#object-namespaces-o-

And can have clear rules on the use of a utility vs. object e.g.

> > Utilities are complete single responsibility rules which have a very specific and targeted task, They are to be used as a last resort when no other CSS hooks are available, or to tackle completely unique circumstances. Can only exist on 1 element.
> > 
> > Objects exist as non-cosmetic styles that handle the skeletal aspect of a lot of UI components, without ever actually looking like designed ‘things’ e.g. **List Inline**.

Last thing I want is making micro components that just exist to be sucked into proper components.

**Comment by chris-pearce** [comment]
Decided! Gonna go with a new section: **Objects** and move applicable utils in there :+1:

**Comment by chris-pearce** [comment]
Addressed in #74.
