### ISSUE TITLE
Move 'Columns' utility to layout

### ISSUE THREAD

**Issue by chris-pearce** [chris-pearce/scally#48]
The [Columns](https://github.com/chris-pearce/scally/blob/master/utilities/_u-columns.scss) utility feels more of a layout module or it goes altogether as it hardly ever gets used?

@kllevin what do you think?

**Comment by kllevin** [comment]
It does feel like a layout thing, but I agree it is hardly ever... I'll think about it a bit more.

**Comment by chris-pearce** [comment]
Fixed in #56.
