### ISSUE TITLE
An easier way to handle different sizes for utilities and components

### ISSUE THREAD

**Issue by chris-pearce** [chris-pearce/scally#49]
```
$spacing-unit: 24px;

$spacing-unit-tiny:  round(0.25 * $spacing-unit);
$spacing-unit-small: round(0.5  * $spacing-unit);
$spacing-unit-large: round(2    * $spacing-unit);
$spacing-unit-huge:  round(4    * $spacing-unit);

@mixin sizes($properties...) {

  &--tiny {
    @each $property in $properties {
      #{$property}: $spacing-unit-tiny;
    }
  }

  &--small {
    @each $property in $properties {
      #{$property}: $spacing-unit-small;
    }
  }

  &--large {
    @each $property in $properties {
      #{$property}: $spacing-unit-large;
    }
  }

  &--huge {
    @each $property in $properties {
      #{$property}: $spacing-unit-huge;
    }
  }

}
```

http://sassmeister.com/gist/87b2da6cbd80d3f1f993, taken from: http://csswizardry.com/2015/03/can-css-be-too-modular/.

@kllevin what do you think?

**Comment by kllevin** [comment]
I like it. Lends itself to more easily applying spacing within components. Would this mean ditching the spacing util? Or this is will also generate that util?

**Comment by chris-pearce** [comment]
@stowball this is that alternative way of applying the spacing stuff, CC: @chriswrightdesign.

**Comment by stowball** [comment]
That's really nice

**Comment by chriswrightdesign** [comment]
That's pretty awesome, it's a good way to deal with varied padding/margin/sizing in general

**Comment by chris-pearce** [comment]
@chriswrightdesign so Scally has a load of [Spacing settings](https://github.com/chris-pearce/scally/blob/master/core/settings/_spacing.scss) which underpins most of your whitespace needs enforcing consistency. The base spacing value comes from the [line-height](https://github.com/chris-pearce/scally/blob/master/core/settings/_spacing.scss#L10) which varies according to the [base font size](https://github.com/chris-pearce/scally/blob/master/core/settings/_typography.scss#L11) ([see](https://github.com/chris-pearce/scally/issues/46)).

The [Spacing utilities](https://github.com/chris-pearce/scally/blob/master/utilities/_u-spacing.scss) feeds from all these spacing settings which you use on UI that isn't a component, like:

```
<div class="u-s-mb-base"> ... </div>
```

And when in a component you would use (if applicable) one of the spacing settings like:

```
.btn {
  @include to-rem(padding-top padding-bottom, $spacing-half);
  @include to-rem(padding-left padding-right, $spacing-base);
}
```

We have found though that they're cases where the spacing settings aren't applicable and where using `em`s over `rem`s is a better fit e.g.

```
.btn {
  @include to-em(padding-top padding-bottom, 8);
  @include to-rem(padding-left padding-right, 16);
}
```

This is mainly when you want your spacing to scale with the font size. But if you're talking a difference of 1-2px then a spacing setting should be used. And the spacing settings should always be used for spacing **outside** (`margin`s) of components e.g. bottom margins, as we want to maintain some sort of vertical rhythm.

---

Scally uses the spacing naming convention of:
- Tiny
- Small
- Base
- Large
- Huge

So I'm thinking we can use a `@mixin` like this to apply those variations of spacing to our components. So yes @kllevin its more for handling those set spacing variations **within** components and the spacing utilities would still remain but for the use case of applying spacing **outside** of the scope of a component, and it wouldn't use a `@mixin` like this, just keep it as is.

**Comment by kllevin** [comment]
:+1: Much cleaner way to handle spacing within components.
