### ISSUE TITLE
Flex Embed name is confusing

### ISSUE THREAD

**Issue by stowball** [chris-pearce/scally#50]
The flex-embed utility is amiguously named. I thought it had something to do with Flexbox at first, but it doesn't.

Alternative suggestions: flexible-embed, fluid-embed, responsive-embed or rwd-embed.

Any of the above would assist users in more easily understanding its purpose from its name,

**Comment by kllevin** [comment]
@chris-pearce I agree the naming is a bit confusing, since you are making a bunch of breaking changes anyway, I would add this to the list. Of the suggestions I would go with 'flexible-embed'

**Comment by chris-pearce** [comment]
Got renamed to `.flexible-embed` and closing as this got done in #47.
