### ISSUE TITLE
Remove these utilities

### ISSUE THREAD

**Issue by chris-pearce** [chris-pearce/scally#60]
In an effort to slim down utilities, along with #47, I'm thinking of removing these utilities completely:
- [Divider](https://github.com/chris-pearce/scally/blob/master/utilities/_u-divider.scss)
- [Image replacement](https://github.com/chris-pearce/scally/blob/master/utilities/_u-image-replacement.scss)
- [Link no underline](https://github.com/chris-pearce/scally/blob/master/utilities/_u-link-no-underline.scss)
- [Cursor](https://github.com/chris-pearce/scally/blob/master/utilities/_u-cursor.scs)

I think all except for _Image replacement_ should just be sucked into the component that needs them and _Image replacement_ is something that is dying out therefore shouldn't really be needed anymore.

**Comment by chris-pearce** [comment]
@stowball @chriswrightdesign @kllevin be good to get your feedback on this, ta.

**Comment by kllevin** [comment]
The only utility in this list I have used with any frequency is divider. That being said, I agree it could easily become part of a component instead. 

Could link no underline become part of  [core](https://github.com/chris-pearce/scally/blob/master/core/base/_links.scss) settings? I can see a need/want to remove text decoration from all links across the project, vs. at the individual component level.

**Comment by chris-pearce** [comment]
> > Could link no underline become part of core settings? I can see a need/want to remove text decoration from all links across the project, vs. at the individual component level.

@kllevin good call and @stowball said a similar thing.

**Comment by chris-pearce** [comment]
Closing as this is covered in #47.
