### ISSUE TITLE
Move List Inline to Layout section

### ISSUE THREAD

**Issue by chris-pearce** [chris-pearce/scally#61]
Not sure about this but the work horse [List inline](https://github.com/chris-pearce/scally/blob/master/utilities/_u-list-inline.scss) utility might be better off as a layout module (in [Layout](https://github.com/chris-pearce/scally/blob/master/layout)) just like the former utility: [Side by side](https://github.com/chris-pearce/scally/blob/master/layout/_l-side-by-side.scss)? I was thinking of making it a component but feel it's a bit too low level for that. Or it stays as a utility?

@kllevin @stowball @Joellepeters @chriswrightdesign what you think?

**Comment by chriswrightdesign** [comment]
It seems more like a component to me since it has the HTML coupling (because of inline-block and whitespace), otherwise I'd maybe put it in layout.

**Comment by chris-pearce** [comment]
Gonna close as decided to move this into the new **Object** section.
