### ISSUE TITLE
Change all instances of "colour" to "color"

### ISSUE THREAD

**Issue by chris-pearce** [chris-pearce/scally#67]
Kills me but might make things easier seeing as the spec uses the American spelling?

```
color: $colour-text;
```

**Comment by kllevin** [comment]
Yay! :us: But seriously I think matching the spec is better.

**Comment by chris-pearce** [comment]
I agree. Still annoys me that the spec went with American spelling :stuck_out_tongue: but such is life.

**Comment by chris-pearce** [comment]
Addressed in #74.
