### ISSUE TITLE
Consider SassDoc comments

### ISSUE THREAD

**Issue by KittyGiraudel** [chris-pearce/scally#94]
Since Scally provides a public Sass API, it might be interesting to consider adding SassDoc comments.

**Comment by chris-pearce** [comment]
SassDoc looks interesting, thanks for the heads up. I'll look into it.

**Comment by KittyGiraudel** [comment]
If you need help to review or set it up, please ask. :)

**Comment by chris-pearce** [comment]
Thanks @HugoGiraudel for the offer, I might just take you up on that offer :)

**Comment by chris-pearce** [comment]
WIll happen in #126.
