### ISSUE TITLE
Better str-replace

### ISSUE THREAD

**Issue by KittyGiraudel** [chris-pearce/scally#96]
There: http://sassmeister.com/gist/1b4f2da5527830088e4d. I think it should be slightly more performant, and easier to understand. :)

**Comment by stowball** [comment]
When using LibSass 3.1.0, the last test case loses the final "e"

**Comment by stowball** [comment]
It turns out that both the old and new suffer with the same LibSass issues. However, the new returns quoted strings, which may or may not make a difference in Scally - I don't know.

http://sassmeister.com/gist/62b001668fbb30806f60

**Comment by KittyGiraudel** [comment]
Reported: https://github.com/sass/libsass/issues/1123.

**Comment by xzyfer** [comment]
This has been fixed in then current Libsass betas.
